### ISSUE TITLE
Audible enemy mechanic

### ISSUE THREAD

**Issue by AlbertoCejas** [mostachostudios/TJ_game#7]
An enemy can hear you only if not walking slowly.

Audible area must be rendered. Ideally must be two levels, if too close (red) -> fail, if still not that close(yellow) -> you still have X seconds to leave that area before it becomes red -> fail.

Angle and radius must be parametrized.

Make use of #5(triggers) and #6(actions)

**Comment by Adrian-Dev** [comment]
Current implementation renders audible area whitin a projected circle on the floor, since the hearing area is a sphere, so only radius is parametrized (it makes more sense to actually use angle in Cone of Sight mechanic). If player moves above a certain speed withing this area, then enemies will hear it, otherwise, player might move without being noticed. Must test it in a level game and see if it is ok this way or if it should become more complex following initial guidelines.

Also, still needs to use triggers and actions to change enemy state

**Comment by Adrian-Dev** [comment]
Updated following initial requirements. Must still refactor it to use triggers and actions
